### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by Fliberatto** [jatmn/Yuoki-Factorio-2.0#2]
I just updated from 1.0 to 2.0.  Can you please help me to sort out this error?

![image](https://github.com/user-attachments/assets/5c76f7b1-b3ff-4cda-8fa4-344639956655)

**Comment by jatmn** [comment]
that issue looks to be related to another mod not Yuoki.
one of the mods you have running is trying to force the icon size to 64x64 when the mod has them set to 32x32.
